# Generated by Django 5.1.5 on 2025-11-15 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bot", "0011_appeal"),
    ]

    operations = [
        migrations.RenameField(
            model_name="telegramuser",
            old_name="participated_quizzes_count",
            new_name="balance",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="best_streak",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="correct_answers",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="current_streak",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="highest_score",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="last_quiz_date",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="total_points",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="total_questions_answered",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="wrong_answers",
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("screenshot_file_id", models.CharField(max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="Bot.telegramuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VideoOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_file_id", models.CharField(max_length=300)),
                (
                    "admin_video_file_id",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("done", "Done"),
                            ("canceled", "Canceled"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_orders",
                        to="Bot.telegramuser",
                    ),
                ),
            ],
        ),
    ]
