# Generated by Django 5.1.5 on 2025-11-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bot", "0012_rename_participated_quizzes_count_telegramuser_balance_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="videoorder",
            old_name="admin_video_file_id",
            new_name="video_file_id",
        ),
        migrations.AddField(
            model_name="videoorder",
            name="amount",
            field=models.IntegerField(default=15000),
        ),
        migrations.AddField(
            model_name="videoorder",
            name="cancel_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
